### ISSUE TITLE
IntegerPolynomial representation of the message

### ISSUE THREAD

**Issue by anirbanbasu** [cygnusv/ntrureencrypt#1]
Hello, I am trying to understand the code (and the paper). What is confusing me is why in `NTRUReEncrypt.java` the `message(byte[] msg)` method creates a random generator seeded by the message. Thus, the actual message data does not contribute to the coefficients of the IntegerPolynomial.

```
IntegerPolynomial m = new IntegerPolynomial(params.N);
Random rand = new SecureRandom(msg);
```

However, I appreciate that for testing the proxy re-encryption concept, the code is still able to generate a random IntegerPolynomial.

**Comment by anirbanbasu** [comment]
Also, how did you measure the timings for Table 4 in [the paper](https://www.nics.uma.es/pub/papers/nunez2015ntrureencrypt.pdf) -- I am getting much slower timings (e.g., about 10x slower) on a machine that is faster than the one you tested on (i.e., my machine is a 2.9GHz Intel Core i5).

**Comment by cygnusv** [comment]
Hi @anirbanbasu! thanks for your interest in this code.
Regarding your questions:
1) yes, you are completely right. This is an absolutely horrendous example of code. I just wanted to test performance so it is not actually encrypting the provided message, but a random message. This is mentioned in a comment in Spanish (https://github.com/cygnusv/ntrureencrypt/blob/master/src/main/java/nics/crypto/ntrureencrypt/NTRUReEncrypt.java#L150). The reason why I did this was to avoid coding an encoding function from a binary message to a trinary polynomial. In any case, the code does encrypt correctly the random message.

2) I'm afraid I don't have the actual code for the performance experiments. I did a big refactoring for uploading to GitHub a couple of years ago and that was probably lost. I do have a text file with the output of some experiments, which is consistent with the table from the paper:

```
run:
        nC  enc  dec decr   re  reky   kg
ep[1]: 100 0,69 1,09 1,02 1,07 20,83 24,03
ep[3]: 100 0,46 1,10 1,22 1,11 23,61 24,97
ep[5]: 100 0,48 1,52 1,72 1,60 35,80 37,33
ep[7]: 100 0,33 0,29 0,32 0,24  4,30  5,07
ep[9]: 100 0,36 0,64 0,54 0,48 10,88 11,50

        nC  enc  dec decr   re  reky   kg
ep[1]: 100 0,58 0,94 0,90 0,96 22,57 25,79
ep[3]: 100 0,47 1,07 1,09 1,06 26,32 27,76
ep[5]: 100 0,41 1,56 1,53 1,50 39,83 41,98
ep[7]: 100 0,52 0,23 0,22 0,19  4,62  5,64
ep[9]: 99  0,35 0,49 0,51 0,45 11,66 12,48

        nC  enc  dec decr   re  reky   kg
ep[1]: 100 0,54 1,01 0,94 1,45 23,54 26,94
ep[3]: 100 0,39 1,10 1,13 1,34 26,98 29,03
ep[5]: 100 0,32 1,49 1,51 1,75 40,67 42,84
ep[7]: 100 0,19 0,26 0,23 0,38  4,91  6,17
ep[9]: 96  0,23 0,58 0,49 0,65 11,94 13,25
```

Each row `ep[i]` represents the timing for a set of parameters. You can map each `i` to the table in the paper using this equivalence:
https://github.com/cygnusv/ntrureencrypt/blob/master/src/main/java/nics/crypto/ntrureencrypt/TestNTRUReEncrypt.java#L18
The result is that the second row of the table is `ep[7]`, the fourth row is `ep[1]`, the sixth row is `ep[3]` and the eight row is `ep[5]`. I don't seem to have the results for the odd rows. 

In any case, all the experiments where performed as described in the paper: 100 iterations for each parameter set, where on each iteration one takes a random message a encrypts it (the timing is column `enc` in the table), re-encrypts it (`re`) and decrypts the re-encrypted ciphertext (`decr`). At the end of the experiment, I take the average for all the encryptions, re-encryptions and decryptions, separately.

**Comment by anirbanbasu** [comment]
Hi @cygnusv, thanks a lot for your response.

(1) Yes, I tried to write a basic encoding replacing your `message()` function for the data by copying the code from the original NtruEncrypt.java as follows.
```
        int l = data.length;
        if (ep.maxMsgLenBytes > 255)
            throw new NtruException("llen values bigger than 1 are not supported");
        if (l > ep.maxMsgLenBytes)
            throw new NtruException("Message too long: " + l + ">" + ep.maxMsgLenBytes);
        byte[] b = new byte[ep.db/8];
        rnd.nextBytes(b);
        byte[] p0 = new byte[ep.maxMsgLenBytes+1-l];
        ByteBuffer mBuf = ByteBuffer.allocate((ep.bufferLenBits+7)/8);
        mBuf.put(b);
        mBuf.put((byte)l);
        mBuf.put(data);
        mBuf.put(p0);
        IntegerPolynomial m = IntegerPolynomial.fromBinary3Sves(mBuf.array(), ep.N, ep.maxM1>0);
        System.out.println("m = " + Arrays.toString(m.coeffs));
```
And, this worked.

(2) I am probably missing something, which is causing me the slower time measurements. Since you do not have the code anymore, you probably don't remember how you measured the times for each primitive? I mean, did you just use things like `System.currentTimeMillis()` or `System.nanoTime()` or external frameworks like Google Guava?

(3) Also, please excuse me for my lack of knowledge about the NTRU cryptosystem: `generateBlindingPolynomial(seed)` is called in the encryption function and also in the re-encryption function. In both those calls, in your code, these are initialised with the same fixed seed. However, does this seed have to be the same? The reason I ask is that the encrypt function in the original NtruEncrypt.java has the following:
```
byte[] sData = getSeed(m, pub, b);
Polynomial r = generateBlindingPoly(sData);
```
If this `sData` has to be the same for the re-encryption, it seems quite impossible to make that happen with its dependency on `m`. Clearly, in your code it isn't dependent on `m` but if the encryption and the re-encryption need to have the same seed, that seed (or the parameters required to generate that seed) ought to be shared between the entity that encrypts and any subsequent proxy?

(4) Have you looked at the proxy re-encryption for some other post-quantum cryptosystem, e.g., the McEliece ones?

Thanks again!

**Comment by cygnusv** [comment]
(1) Great :) If tests pass, you can make a PR if you want.

(2) I measured with `System.nanoTime()`, right before and after of each function call. 

(3) The seed doesn't have to be shared.

(4) No, sorry

**Comment by anirbanbasu** [comment]
(1) Thanks, that's a good idea :-)

(2) I will check with `System.nanoTime()` and try again. I used Google Guava.

(3) That's great!

(4) Ok.

**Comment by anirbanbasu** [comment]
Just a quite note @cygnusv - finally, my results are as I expect, i.e., faster than the ones in your paper simply because I am testing on a faster hardware. Thanks for your support.

**Comment by cygnusv** [comment]
oh great! that makes sense. Thanks for letting me know. BTW, are you writing a paper?

**Comment by anirbanbasu** [comment]
Yes, I am writing a paper and citing your NTRUReEncryption work as one of the cryptosystems we could use in our paper.
